version: '3'

tasks:
  install:
    desc: "Install xamin"
    cmds:
      - pip install .
  develop:
    desc: "Install xamin in (editable) developer mose"
    cmds:
      - pip install --editable .[testing]
